// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReadMyBrainAPI.Models;

namespace read_my_brain_api.Migrations
{
    [DbContext(typeof(ReadMyBrainAPIContext))]
    [Migration("20200509164858_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReadMyBrainAPI.Models.Term", b =>
                {
                    b.Property<int>("TermID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("TermID");

                    b.ToTable("Terms");

                    b.HasData(
                        new
                        {
                            TermID = 1,
                            Definition = "Male",
                            Name = "M"
                        },
                        new
                        {
                            TermID = 2,
                            Definition = "Female",
                            Name = "F"
                        },
                        new
                        {
                            TermID = 3,
                            Definition = "History of",
                            Name = "Hx"
                        },
                        new
                        {
                            TermID = 4,
                            Definition = "history of",
                            Name = "hx"
                        },
                        new
                        {
                            TermID = 5,
                            Definition = "Allergy of",
                            Name = "Ax"
                        },
                        new
                        {
                            TermID = 6,
                            Definition = "Do Not Resuscitate",
                            Name = "DNR"
                        },
                        new
                        {
                            TermID = 7,
                            Definition = "immediately",
                            Name = "STAT"
                        },
                        new
                        {
                            TermID = 8,
                            Definition = "patient",
                            Name = "pt"
                        },
                        new
                        {
                            TermID = 9,
                            Definition = "patient",
                            Name = "Pt"
                        },
                        new
                        {
                            TermID = 10,
                            Definition = "Physical Therapist",
                            Name = "PT"
                        },
                        new
                        {
                            TermID = 11,
                            Definition = "with",
                            Name = "c̅"
                        },
                        new
                        {
                            TermID = 12,
                            Definition = "before",
                            Name = "ā"
                        },
                        new
                        {
                            TermID = 13,
                            Definition = "after",
                            Name = "p̄"
                        },
                        new
                        {
                            TermID = 14,
                            Definition = "Medical Doctor",
                            Name = "MD"
                        },
                        new
                        {
                            TermID = 15,
                            Definition = "Registered Nurse",
                            Name = "RN"
                        },
                        new
                        {
                            TermID = 16,
                            Definition = "Surgery",
                            Name = "Sx"
                        },
                        new
                        {
                            TermID = 17,
                            Definition = "surgery",
                            Name = "sx"
                        },
                        new
                        {
                            TermID = 18,
                            Definition = "hypertension",
                            Name = "HTN"
                        },
                        new
                        {
                            TermID = 19,
                            Definition = "diabetes mellitus",
                            Name = "DM"
                        },
                        new
                        {
                            TermID = 20,
                            Definition = "right total knee arthroplasty",
                            Name = "RTKA"
                        },
                        new
                        {
                            TermID = 21,
                            Definition = "left total knee arthroplasty",
                            Name = "LTKA"
                        },
                        new
                        {
                            TermID = 22,
                            Definition = "chest x-ray",
                            Name = "CXR"
                        },
                        new
                        {
                            TermID = 23,
                            Definition = "Emergency Department",
                            Name = "ED"
                        },
                        new
                        {
                            TermID = 24,
                            Definition = "alert and oriented",
                            Name = "A&O"
                        },
                        new
                        {
                            TermID = 25,
                            Definition = "alert and oriented x 1",
                            Name = "A&Ox1"
                        },
                        new
                        {
                            TermID = 26,
                            Definition = "alert and oriented x 2",
                            Name = "A&Ox2"
                        },
                        new
                        {
                            TermID = 27,
                            Definition = "alert and oriented x 3",
                            Name = "A&Ox3"
                        },
                        new
                        {
                            TermID = 28,
                            Definition = "alert and oriented x 4",
                            Name = "A&Ox4"
                        },
                        new
                        {
                            TermID = 29,
                            Definition = "penicillin",
                            Name = "pnc"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
